### ISSUE TITLE
Context collision with context.Context, breaking change proposal

### ISSUE THREAD

**Issue by huttarichard** [rogchap/v8go#153]
Usually if you are doing something with v8go or generally with go, you want to have around context.Context.

I started by wrapping this library into my own structures and I had my own `Isolate` looking like this:

```golang
type Isolate {
  *v8go.Isolate
  ctx context.Context
}
```

However you cannot really use that that unless you wrap `*v8go.Context` as well. And in the end you need to also wrap most of other functionality to carry that context around.

It would be convenient if isolate `v8go.Isolate` could have `WithContext()` and `Context()`and would terminate execution on cancel.

Breaking change I propose is to change `v8go.Context` to `ExecutionContext` to clearly distinguish between the two.  
`Isolate` can then provide `Context()` method and its not going to be confusing (people in c++ world dont really know what golang context is, therefore I think it make sense not to follow their naming conventions.)

Later down the road it will be handy to have it with functional template:

```go
v8go.NewFunctionTemplate(iso.Isolate, func(info) {
   ... do some stuff
   select {
   case <-info.Context().Done():
      return 
   }
})
```

that way we can on cancel of the context terminate execution fully with in go as well.

**Comment by dylanahsmith** [comment]
It seems like it is idiomatic in Go to let the package name provide disambiguation for types.  For instance, Go doesn't provide HttpRequest and RpcRequest as types in the standard library and instead leverages the package names to expose them as [`http.Request`](https://golang.org/pkg/net/http/#Request) and [`rpc.Request`](https://golang.org/pkg/net/rpc/#Request).  Similarly, there is `context.Context` and `v8go.Context` (actually `v8` would have been a better package name for this library, but at least you can rename on import to be `v8.Context`).

This only becomes a problem when a package has two types of contexts, as is the case in your wrapper library, so you can do whatever disambiguation you deem appropriate there.  As such, it is a concern brought up in https://github.com/rogchap/v8go/issues/80 for adding context.Context support to this library, since any naming should be decided specifically in the context of that issue.  As such, I think this issue should be closed, since it only matters in the context of adding that feature to this library.

**Comment by huttarichard** [comment]
I do agree :) didn't notice the the #80. We can have more of discussion there.
