### ISSUE TITLE
Calling an instance method that uses `this` fails with `undefined`

### ISSUE THREAD

**Issue by genevieve** [rogchap/v8go#156]
I have a Response object with a constructor that accepts a body as argument, and has a method called `text()` that returns said body as string. When I get the response as an object and call the method, I get `Cannot read property 'body' of undefined`.

Here's the example go code:
```go
package main

import (
	"fmt"
	"io/ioutil"

	"rogchap.com/v8go"
)

func main() {
	script, _ := ioutil.ReadFile("script.js")
	iso, _ := v8go.NewIsolate() // creates a new JavaScript VM
	ctx, _ := v8go.NewContext(iso)
	val, _ := ctx.RunScript(string(script), "script.js")
	respObj, _ := val.AsObject()
	textVal, _ := respObj.Get("text")
	textFn, _ := textVal.AsFunction()
	body, err := textFn.Call()
	if err != nil {
		panic(err)
	}
	fmt.Println(body)
}
```

Here's the script:
```js
class Response {
  constructor(body) {
    this.body = body;
  }
  text() {
    return this.body.toString();
  }
}

new Response("this body");
```

Here's the error:
```
panic: TypeError: Cannot read property 'body' of undefined

goroutine 1 [running]:
main.main()
	/Users/genevieve/workspace/test/main.go:35 +0x37c
exit status 2
```

I'm assuming I'm doing something wrong but not sure exactly what it is. Any guidance is appreciated 🙏🏻 

EDIT: There might be parts of https://github.com/rogchap/v8go/pull/142/files that are relevant.

EDIT 2: Questions - Should a v8go function support `bind()`? Should a v8go function keep a reference to the object it belongs to with an internal `this` ptr? Is this function not really executing directly on the instance of response that I think it is?

**Comment by dylanahsmith** [comment]
What you are doing from Go corresponds to javascript like

```
r = new Response("this body")
f = r.text
f()
```

which gets the same error, since a function object doesn't carry a receiver with it.

The implicit passing of `undefined` as the receiver seems like an unfortunate gotcha to the javascript language, which more experienced javascript developers may be familiar with, but can easily cause confusion when first encountered.

v8's API more closely follows the [Function.prototype.call javascript method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) in passing the receiver explicitly, but actually requires the receiver a required parameter.  This avoids the confusion of implicitly passing `undefined`.

It seems like v8go's Function.Call method tries to provide an API that gophers would expect, but with behaviour that they wouldn't expect.  Making go developers pass the receiver explicitly seems better, since it would give them the behaviour that they would expect so they avoid this confusion.  This would also follow v8's original API which is another project goal.

> Would it be reasonable for the v8go object to expose a method like `Call(fnName string, args ...Valuer)` so it executes the method directly on the instance of the object? It doesn't even seem like there's a way to do that with v8 in c++ - https://v8docs.nodesource.com/node-0.8/db/d85/classv8_1_1_object.html

In terms of naming, we might want to avoid confusion with two ways an object itself can actually be called [v8::Object::CallAsFunction](https://v8.github.io/api/head/classv8_1_1Object.html#aa8cf4c62cc78f25149b7cc75b23fb5bd) and [v8::Object::CallAsConstructor](https://v8.github.io/api/head/classv8_1_1Object.html#ade4e79ff6616ddca964944bed248035f).  Since it isn't the object itself being called in this case, perhaps MethodCall would be a more appropriate name.

I think that would be useful as a convenience method to for this use case.  However, the change to Function.Call would provide the more general capability of passing an explicit receiver to a function and avoid additional confusion around the fact that functions obtained from an object are not bound to the object they are obtained from.
