### ISSUE TITLE
How can scripts that rely on web workers work with v8go

### ISSUE THREAD

**Issue by siddharthlatest** [rogchap/v8go#247]
Is it possible to run JS scripts that rely on web workers? (Is this is more of a V8/CGO limitation v/s what this project can do?) Many interesting libraries (e.g. tesseract.js, Flexsearch) rely on web workers.

I attempted running tesseract.js, downloaded from [here](https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/2.1.5/tesseract.min.js) as follows:

```go
package main

import (
	"fmt"

	v8 "rogchap.com/v8go"
)

func main() {
	iso := v8.NewIsolate()
	// go:embed js/tesseract.js
	var ocrScript string

	ocrCtx := v8.NewContext(iso)

	_, err := ocrCtx.RunScript(ocrScript, "tesseract.js")
	if err != nil {
		fmt.Println("error while loading tesseract context", err)
	}
	script := `
	Tesseract.recognize(
		'https://tesseract.projectnaptha.com/img/eng_bw.png',
		'eng'
	).then(function(data) {
		return data;
	});`

	res, err := ocrCtx.RunScript(script, "script.js")
	if err != nil {
		fmt.Println("error while running user script: ", err)
	}
	if res != nil {
		fmt.Println("returned value is: ", res)
	}
}
```

```
error while running user script:  ReferenceError: Tesseract is not defined
```

The error I get is related to `Tesseract` not being available in the context.

**Comment by dylanahsmith** [comment]
V8 doesn't provide web APIs so JS written for the browser won't just work in V8.  V8 is used in the chrome web browser, so there isn't a V8 limitation that would prevent adding support for it.  V8 isolates are single threaded, so I think it would involve having a separate isolate for the worker, with some code using V8 (e.g. through v8go) to pass messages between the isolates.

I'll close this since it is out of scope of v8go
