### ISSUE TITLE
[Question]How to define async function in Go?

### ISSUE THREAD

**Issue by Laisky** [rogchap/v8go#288]
Is it possible to define an async function in Go that return `Promise` in JS ?

**Comment by dylanahsmith** [comment]
[PromiseResolver](https://pkg.go.dev/rogchap.com/v8go#PromiseResolver) can be used to create and resolve a promise in Go.

**Comment by Laisky** [comment]
> [PromiseResolver](https://pkg.go.dev/rogchap.com/v8go#PromiseResolver) can be used to create and resolve a promise in Go.

* `NewPromiseResolver(ctx)` need ctx, and ctx created after `v8.NewContext(iso, global)`, so ctx need global
* `NewPromiseResolver(ctx)` called before `global.Set(FuncName, GoFunc)`,  so global need ctx

that is a dilemma, I could not figure how to solve it.

Could you kindly give an example?

**Comment by dylanahsmith** [comment]
The documentation has an example that uses PromiseResolver: https://pkg.go.dev/rogchap.com/v8go#example-FunctionTemplate-Fetch

> * `NewPromiseResolver(ctx)` called before `global.Set(FuncName, GoFunc)`

I'm not sure why that is the case.  You don't need the promise resolver to define the async function, you just need it to create the promise to return from an async function such that it can be resolved from Go code.  As such, you would typically use NewPromiseResolver when that function that is exposed to JS is called, so that a different promise is returned each time.

**Comment by Laisky** [comment]
Thanks so much! @dylanahsmith 

`info.Context()` solve my problem.
