### ISSUE TITLE
More background info?

### ISSUE THREAD

**Issue by intel352** [rogchap/v8go#37]
A few questions I have about this repo:

- It says pre-built binaries are included. Is this simply to reduce rebuild complexity, or is there another reason?
- Pre-built binaries are only provided for linux and osx, what about windows, bsd, etc? Aside from reducing your own build complexity, is there any reason those platforms are omitted?
- I saw mention of C, why is C used instead of rewriting v8 in pure go?
- Another interpreter, **otto**, is written in Go, but has some limitations, such as Go doesn't support backtracking in regex which means those regex patterns aren't supported in the executed js. I assume this library isn't impacted since it doesn't use pure go?

- What's the author's use case for this repo? Curious what problems you solved for yourself by tying v8 to go.

**Comment by trusch** [comment]
I really don't want to troll here, but this needs to be said: You can use otto to have a fairly complete js interpreter for ECMAscript 5. But if you want to really extensively use JS in your application, then you kind of need to use the v8 engine just because its the most mature implementation of the ECMAscript(6, 7?) standard. Rewriting the v8 engine in pure go would be more work than you can imagine. If you look at the issue tracker of the v8 engine you will see nearly 10k closed issues and the repo has over 65k commits. Sounds like the job of a bit more than a few weekends.

If you want to to see a more practical example, try to run this in otto:
```go
package main

import (
	"fmt"

	"github.com/rs/zerolog/log"
	"rogchap.com/v8go"
)

// from https://github.com/v8/v8/blob/master/samples/hello-world.cc
const code = `
let bytes = new Uint8Array([
   0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x07, 0x01,
   0x60, 0x02, 0x7f, 0x7f, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07,
   0x07, 0x01, 0x03, 0x61, 0x64, 0x64, 0x00, 0x00, 0x0a, 0x09, 0x01,
   0x07, 0x00, 0x20, 0x00, 0x20, 0x01, 0x6a, 0x0b
]);
let module = new WebAssembly.Module(bytes);
const webasm = new WebAssembly.Instance(module);`

func main() {
	vm, _ := v8go.NewIsolate()    // creates a new JavaScript VM
	ctx, _ := v8go.NewContext(vm) // new context within the VM
	_, err := ctx.RunScript(code, "webassembler.js")
	if err != nil {
		log.Fatal().Err(err).Msg("failed to setup webassembler")
	}
	val, err := ctx.RunScript("webasm.exports.add(3, 4)", "main.js")
	if err != nil {
		log.Fatal().Err(err).Msg("failed to run script")
	}
	fmt.Printf("val: %v\n", val)
}
``` 
I really appreciate this library and how easy it is to use. It worked out of the box for me and its not the first v8 wrapper I tried.
Also, as far as I can tell, this is the best maintained wrapper :) 

@rogchap please remove this comment if its too unconstructive, I really don't want to offend anyone.

**Comment by tmc** [comment]
I think this issue should be closed and the README could be extended with some information about the intended scope of the project. Adding prepared binaries for more platforms is surely a welcome contribution and contributors should feel free to step forward and assit.

**Comment by intel352** [comment]
More info in the Readme would make me happy. I wasn't critiquing the library, just wanting to understand a few choices.

**Comment by rogchap** [comment]
I've update the readme to include project goals:
> To provide a high quality, idiomatic, Go binding to the V8 C++ API.
>
> The API should match the original API as closely as possible, but with an API that Gophers (Go enthusiasts) expect. For example: using multiple return values to return both result and error from a function, rather than throwing an exception.
>
> This project also aims to keep up-to-date with the latest (stable) release of V8.
