### ISSUE TITLE
pre-compiling code

### ISSUE THREAD

**Issue by konethmelathil** [rogchap/v8go#84]
Is there a way to pre-compile code to be run over and over again for performance vs evaluating always at the golang bindings level?
as in:

/v8go.cc: 394

  MaybeLocal<Script> script = Script::Compile(local_ctx, src, &script_origin);
  if (script.IsEmpty()) {
    rtn.error = ExceptionError(try_catch, iso, local_ctx);
    return rtn;
  }

**Comment by rogchap** [comment]
Hey @konethmelathil;

You can create a function in the context with either `RunScript()` or use a `FunctionTemplate` and you can just call that function again and again without having to complie the whole script. 

At the moment there is no way to access the complied script directly (due to the RunScript abstraction); but this could possibly be added in the future as it's along the right lines of the project goals.

**Comment by sefgit** [comment]
What about "cloning" a  preloaded context into a new isolated context ?
Would that work ?

One can use these cloned isolated contexts in goroutines concurrently, right ?

**Comment by sefgit** [comment]
taken from manual:

` An *Isolate can be used as a v8go.ContextOption to create a new Context, rather than creating a new default Isolate.`

**Comment by genevieve** [comment]
@konethmelathil If this is still an issue for you, you may be able to use the new functionality from https://github.com/rogchap/v8go/pull/206

**Comment by genevieve** [comment]
Closing since https://github.com/rogchap/v8go/releases/tag/v0.7.0 was released with the changes in #206
