### ISSUE TITLE
Add Isolate.ThrowException(exception) support

### ISSUE THREAD

**Issue by robfig** [rogchap/v8go#90]
Thanks for amazing project! Very exciting to be able to use v8 so easily.

I'm providing my JS script an API implemented with a Go FunctionCallback. If an error occurs, how do I signal that to the caller? Throwing a JS error seems like the correct route, but I don't see any way to do that. 

For example

```go
	
	global, _ := v8go.NewObjectTemplate(iso)
	fn, _ := v8go.NewFunctionTemplate(iso, func(info *v8go.FunctionCallbackInfo) *v8go.Value {
		// HOW TO RAISE A JS ERROR?
		return nil
	})
	global.Set("myfn", fn)
```

Thank you

**Comment by rogchap** [comment]
Hey @robfig 
Thanks for your interest in the project. 
This is unfortunately not possible 😢 
I had tried to get this to work as part of the Basic Promise PR, but I had issues creating Error values... just kept crashing. 
I left it out for now but plan to work on it to have it working again. Ref: https://github.com/rogchap/v8go/pull/76#issuecomment-788828459

**Comment by dylanahsmith** [comment]
If you use the latest changes on master, then there is now a Function.NewInstance function that can be used to call a function as a constructor (e.g. like `new Error(message)`).  I think the only thing left is to add an Isolate.ThrowException method.

A workaround would be to execute some JS code to throw the exception (or define a function to do that).  This code is on the slow path, so that may be acceptable.
